# The game of Nim: The Chinese game of nim is played as follows.  There are several piles of matches, each containing
# an arbitrary number of matches at the start of the game.  To make a move a player removes one or more matches
# from one of the piles.  The players take turns, and the player who removes the last match wins the game.
################################################################################################################
# create a piles of matches, this can be any number of piles from 2 to 6 ( you can change for more or less if desired)
# this is randomly generated by the code below.  Then, in each pile, there can be a random number of matches, here
# it is set to an integer from 1 to 11.  This can be changed as desired as well.
################################################################################################################

piles_of_matches <- c()
No_of_piles<-floor(runif(1,min=2,max=6))
for (i in 1:No_of_piles){
  piles_of_matches<-append(piles_of_matches, floor(runif(1,min=1,max=11)),after=length(piles_of_matches))
}
piles_of_matches
################################################################################################################
# this function pick_pile prompts the player to pick a pile of matches to pick from.
# x is coerced into an integer, if it is not an integer as.integer(x) converts x to NA, and this is tested for
# before proceeding.  One also must be careful that the x is within the range of the number of piles that exist.
# If it is not an integer or is an invalid choice (x <= 0 or x >length(piles_of_matches)), the player is reprompted until a valid integer x is input.
################################################################################################################
pick_pile <- function(){
  x <<- readline("pick a pile of matches to take from:")
  x <<- as.integer(x)
  if (is.na(x) || x <= 0 || x >length(piles_of_matches) || is.na(piles_of_matches[x]) || piles_of_matches[x] == 0 ) {pick_pile()}
  return(x)
}
##################################################################################################################
# Once the pile of matches is selected, the player must then choose how many matches to take from the selected pile
# again, this input must be valid under similar conditions as above.
###################################################################################################################

pick_no_matches <- function(){
  y <<- readline("how many matches will you take?")
  y <<- as.integer(y)
  if (is.na(y) || y > piles_of_matches[x] || y <= 0) {pick_no_matches()}
  return(y)
}
#################################################################################################################
# Once the pile is selected and the number of matches to take is chosen, the action is executed in the function below.
# this updates the piles of matches accordingly.
##################################################################################################################
 
play_action <- function(x,y) {
  if ( x >=1 && x <= length(piles_of_matches)) {
    if (y >=1 && y <= piles_of_matches[x]){
      piles_of_matches[x] <<- piles_of_matches[x]-y
      return(piles_of_matches)
    }else {pick_no_matches()}
  }else {pick_pile()}
}
################################################################################################################
# below is the game final product.  The game continues until the sum of the piles of matches is zero - that is, when
# there are no more matches to pick.  The player that picked the last match wins the game. 
# Find another player and try it out!
################################################################################################################
j <-0
while (sum(piles_of_matches) != 0){
      print(piles_of_matches)
       if (j %% 2 == 0){
                print("player 1's turn")
                play_action(x=pick_pile(),y=pick_no_matches())
                j <- j+1
                  if (sum(piles_of_matches) == 0){print("player 1 wins!")}else{next}
      } else {print("player 2's turn")
             play_action(x=pick_pile(),y=pick_no_matches())
             j <- j+1
                  if (sum(piles_of_matches) == 0){print("player 2 wins!")}else{next}
      }
   
}

